---
- block:
  - name: Install Nginx
    yum:
      name: nginx
      state: present

  - name: Install policycoreutils-python (for SELinux management)
    yum:
      name: policycoreutils-python
      state: present

  - name: Copy nginx loging configuration template
    template:
      src: syslog.conf
      dest: /etc/nginx/conf.d/syslog.conf
      owner: root
      group: root
      mode: 0644

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Start and enable Nginx service
    service:
      name: nginx
      state: started
      enabled: yes
  become: yes