---
- block:
  - name: Add repository for syslog-ng
    yum_repository:
      name: czanik-syslog-ng
      description: Copr repo for syslog-ng314 owned by czanik
      baseurl: "{{ syslogng_repo_baseurl }}"
      gpgkey: "{{ syslogng_repo_gpgkey }}"
      gpgcheck: yes
      enabled: yes
  
  - name: Install syslog-ng
    yum:
      name: syslog-ng
      state: present
  
  - name: Install syslog-ng-redis plugin
    yum:
      name: syslog-ng-redis
      state: present
  
  - name: Uninstall rsyslog
    yum:
      name: rsyslog
      state: absent

  - name: Copy nginx loging configuration template
    template:
      src: redis.conf
      dest: /etc/syslog-ng/conf.d/redis.conf
      owner: root
      group: root
      mode: 0644

  - name: Start and enable syslog-ng service
    service:
      name: syslog-ng
      state: started
      enabled: yes
  become: yes